Web Scraping

!pip install webdriver-manager

!pip install selenium

!pip install html5lib

In [1]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
import time
import pandas as pd

## Processo de dados

*Abrir o site
*mudar a vizualização para o maximo
*ler tabela
*avançar todas as paginas
*trocar para outra categoria
*ler todas as tabelas dessa outra categoria

In [2]:
driver = webdriver.Chrome(service = Service(ChromeDriverManager().install()))

url = "https://www.etf.com/etfanalytics/etf-finder"

driver.get(url)

# achar a maior visualização

In [3]:
#esperar o JavaScript carregar
time.sleep(5)
#achar elemento + inspecionar + copy fullpath

botao_100 = driver.find_element("xpath", '''/html/body/div[5]/section/div/div[3]/section/div/div/div/div/div[2]/section[2]/div[2]/section[2]/div[1]/div/div[4]/button/label/span''')

driver.execute_script("arguments[0].click();", botao_100)

Numero de paginas

In [4]:
numero_paginas = driver.find_element("xpath", '''/html/body/div[5]/section/div/div[3]/section/div/div/div/div/div[2]/section[2]/div[2]/section[2]/div[2]/div/label[2]''')

print(numero_paginas.text)

of 31

In [5]:
numero_paginas = numero_paginas.text.replace("of ","")

numero_paginas = int(numero_paginas)

print(numero_paginas)

31

# LOOP

In [6]:
# Fazer o Loop para ler as paginas

lista_de_tabelas_por_pagina = []

for pagina in range (0, numero_paginas):
    tabela = driver.find_element("xpath", '''/html/body/div[5]/section/div/div[3]/section/div/div/div/div/div[2]/section[2]/div[2]/div''')

    html_tabela = tabela.get_attribute("outerHTML")
    
    tabela_final = pd.read_html(html_tabela)[0]
    
    lista_de_tabelas_por_pagina.append(tabela_final)
    
    botao_avancar_pagina = driver.find_element("xpath", '''/html/body/div[5]/section/div/div[3]/section/div/div/div/div/div[2]/section[2]/div[2]/section[2]/div[2]/div/span[2]''')
    
    driver.execute_script("arguments[0].click();", botao_avancar_pagina)
    
base_de_dados_completa = pd.concat(lista_de_tabelas_por_pagina)

display(base_de_dados_completa)

,Ticker,Name,Segment,Issuer,Expense Ratio,AUM
0,SPY,SPDR S&P 500 ETF Trust,Equity: U.S. - Large Cap,State Street Global Advisors,0.09%,$379.11B
1,IVV,iShares Core S&P 500 ETF,Equity: U.S. - Large Cap,Blackrock,0.03%,$310.04B
2,VTI,Vanguard Total Stock Market ETF,Equity: U.S. - Total Market,Vanguard,0.03%,$284.32B
3,VOO,Vanguard S&P 500 ETF,Equity: U.S. - Large Cap,Vanguard,0.03%,$282.26B
4,QQQ,Invesco QQQ Trust,Equity: U.S. - Large Cap,Invesco,0.20%,$161.85B
...,...,...,...,...,...,...
85,AWYX,ETFMG 2x Daily Travel Tech ETF,Leveraged Equity: Global Internet & Direct Mar...,ETFMG,0.95%,$335.16K
86,TADS,The Active Dividend Stock ETF,Equity: U.S. - Total Market,"Tuttle Tactical Management, LLC",1.68%,$294.89K
87,CRYP,AdvisorShares Managed Bitcoin Strategy ETF,Asset Allocation: Global Target Outcome,AdvisorShares,1.59%,$215.63K
88,FLRU,Franklin FTSE Russia ETF,Equity: Russia - Total Market,Franklin Templeton,0.19%,$8.00K
89,NBCM,Neuberger Berman Commodity Strategy ETF,Commodities: Broad Market,Neuberger Berman,0.65%,--

In [7]:
#pegar a segunda aba

botao_aba = driver.find_element("xpath", '''/html/body/div[5]/section/div/div[3]/section/div/div/div/div/div[2]/section[2]/div[2]/ul/li[2]/span''')

driver.execute_script("arguments[0].click();", botao_aba)

#voltar para 1 pagina

for pagina in range (0, numero_paginas):
    botao_voltar_pagina = driver.find_element("xpath", '''/html/body/div[5]/section/div/div[3]/section/div/div/div/div/div[2]/section[2]/div[2]/section[2]/div[2]/div/span[1]''')
    driver.execute_script("arguments[0].click();", botao_voltar_pagina)
    
    
lista_de_tabelas_por_pagina = []

In [8]:
for pagina in range (0, numero_paginas):
    tabela = driver.find_element("xpath", '''/html/body/div[5]/section/div/div[3]/section/div/div/div/div/div[2]/section[2]/div[2]/div''')

    html_tabela = tabela.get_attribute("outerHTML")
    
    tabela_final = pd.read_html(html_tabela)[0]
    
    lista_de_tabelas_por_pagina.append(tabela_final)
    
    botao_avancar_pagina = driver.find_element("xpath", '''/html/body/div[5]/section/div/div[3]/section/div/div/div/div/div[2]/section[2]/div[2]/section[2]/div[2]/div/span[2]''')
    
    driver.execute_script("arguments[0].click();", botao_avancar_pagina)
    
base_de_dados_performace = pd.concat(lista_de_tabelas_por_pagina)

display(base_de_dados_performace)

,Ticker,Name,1 Month,3 Month,YTD,1 Year,3 Years,5 Years,10 Years,As Of Date
0,SPY,SPDR S&P 500 ETF Trust,4.03%,8.84%,3.52%,-9.95%,7.75%,8.99%,12.39%,01/20/23
1,IVV,iShares Core S&P 500 ETF,4.06%,8.84%,3.51%,-9.95%,7.75%,9.03%,12.44%,01/20/23
2,VTI,Vanguard Total Stock Market ETF,4.49%,8.98%,3.96%,-10.36%,7.24%,8.49%,12.02%,01/20/23
3,VOO,Vanguard S&P 500 ETF,4.02%,8.82%,3.52%,-9.98%,7.73%,9.02%,12.44%,01/20/23
4,QQQ,Invesco QQQ Trust,4.88%,5.30%,6.16%,-21.28%,8.84%,11.98%,16.55%,01/20/23
...,...,...,...,...,...,...,...,...,...,...
85,AWYX,ETFMG 2x Daily Travel Tech ETF,36.11%,38.66%,31.27%,-48.46%,--,--,--,01/20/23
86,TADS,The Active Dividend Stock ETF,0%,0%,0%,0%,--,--,--,01/20/23
87,CRYP,AdvisorShares Managed Bitcoin Strategy ETF,--,--,--,--,--,--,--,01/20/23
88,FLRU,Franklin FTSE Russia ETF,0%,0%,0%,-66.37%,-31.18%,--,--,01/20/23
89,NBCM,Neuberger Berman Commodity Strategy ETF,4.82%,--,1.82%,--,--,--,--,01/20/23

In [9]:
driver.quit()

In [10]:
#juntar as tabelas - atraves de uma chave
base_de_dados_completa = base_de_dados_completa.set_index("Ticker")

In [11]:
base_de_dados_performace = base_de_dados_performace.set_index("Ticker")

In [12]:
base_de_dados_performace = base_de_dados_performace[["1 Year", "5 Years", "10 Years"]]
base_de_dados_performace

         1 Year 5 Years 10 Years
Ticker
SPY      -9.95%   8.99%   12.39%
IVV      -9.95%   9.03%   12.44%
VTI     -10.36%   8.49%   12.02%
VOO      -9.98%   9.02%   12.44%
QQQ     -21.28%  11.98%   16.55%
...         ...     ...      ...
AWYX    -48.46%      --       --
TADS         0%      --       --
CRYP         --      --       --
FLRU    -66.37%      --       --
NBCM         --      --       --

[3090 rows x 3 columns]

In [13]:
base_dados_final = base_de_dados_completa.join(base_de_dados_performace)
base_dados_final

,Name,Segment,Issuer,Expense Ratio,AUM,1 Year,5 Years,10 Years
Ticker,,,,,,,,
SPY,SPDR S&P 500 ETF Trust,Equity: U.S. - Large Cap,State Street Global Advisors,0.09%,$379.11B,-9.95%,8.99%,12.39%
IVV,iShares Core S&P 500 ETF,Equity: U.S. - Large Cap,Blackrock,0.03%,$310.04B,-9.95%,9.03%,12.44%
VTI,Vanguard Total Stock Market ETF,Equity: U.S. - Total Market,Vanguard,0.03%,$284.32B,-10.36%,8.49%,12.02%
VOO,Vanguard S&P 500 ETF,Equity: U.S. - Large Cap,Vanguard,0.03%,$282.26B,-9.98%,9.02%,12.44%
QQQ,Invesco QQQ Trust,Equity: U.S. - Large Cap,Invesco,0.20%,$161.85B,-21.28%,11.98%,16.55%
...,...,...,...,...,...,...,...,...
AWYX,ETFMG 2x Daily Travel Tech ETF,Leveraged Equity: Global Internet & Direct Mar...,ETFMG,0.95%,$335.16K,-48.46%,--,--
TADS,The Active Dividend Stock ETF,Equity: U.S. - Total Market,"Tuttle Tactical Management, LLC",1.68%,$294.89K,0%,--,--
CRYP,AdvisorShares Managed Bitcoin Strategy ETF,Asset Allocation: Global Target Outcome,AdvisorShares,1.59%,$215.63K,--,--,--
FLRU,Franklin FTSE Russia ETF,Equity: Russia - Total Market,Franklin Templeton,0.19%,$8.00K,-66.37%,--,--
NBCM,Neuberger Berman Commodity Strategy ETF,Commodities: Broad Market,Neuberger Berman,0.65%,--,--,--,--

### Fazer Ranking de ETF´s

In [14]:
# escolher periodo de rentabilidadeabs (1, 3, 5)
base_de_dados_performace = base_de_dados_performace [["1 Year", "5 Years", "10 Years"]]
base_de_dados_performace

         1 Year 5 Years 10 Years
Ticker
SPY      -9.95%   8.99%   12.39%
IVV      -9.95%   9.03%   12.44%
VTI     -10.36%   8.49%   12.02%
VOO      -9.98%   9.02%   12.44%
QQQ     -21.28%  11.98%   16.55%
...         ...     ...      ...
AWYX    -48.46%      --       --
TADS         0%      --       --
CRYP         --      --       --
FLRU    -66.37%      --       --
NBCM         --      --       --

[3090 rows x 3 columns]

In [15]:
base_de_dados_performace = base_de_dados_performace.replace("--", pd.NA)
base_de_dados_performace

         1 Year 5 Years 10 Years
Ticker
SPY      -9.95%   8.99%   12.39%
IVV      -9.95%   9.03%   12.44%
VTI     -10.36%   8.49%   12.02%
VOO      -9.98%   9.02%   12.44%
QQQ     -21.28%  11.98%   16.55%
...         ...     ...      ...
AWYX    -48.46%     NaN      NaN
TADS         0%     NaN      NaN
CRYP       <NA>     NaN      NaN
FLRU    -66.37%     NaN      NaN
NBCM       <NA>     NaN      NaN

[3090 rows x 3 columns]

In [16]:
base_de_dados_performace = base_de_dados_performace.dropna()
base_de_dados_performace

         1 Year  5 Years 10 Years
Ticker
SPY      -9.95%    8.99%   12.39%
IVV      -9.95%    9.03%   12.44%
VTI     -10.36%    8.49%   12.02%
VOO      -9.98%    9.02%   12.44%
QQQ     -21.28%   11.98%   16.55%
...         ...      ...      ...
SZK      36.84%  -20.50%  -22.95%
LD       -8.85%   -5.95%   -1.99%
ERUS    -78.73%  -23.10%  -13.14%
LTL     -31.34%   -2.87%    2.44%
RSXJ    -62.94%  -20.41%  -10.41%

[893 rows x 3 columns]

In [26]:
base_de_dados_performace['1 Year'] = (base_de_dados_performace['1 Year'].astype(float))

base_de_dados_performace['5 Years'] = (base_de_dados_performace['5 Years'].str.rstrip('%').astype(float))

base_de_dados_performace['10 Years'] = (base_de_dados_performace['10 Years'].str.rstrip('%').astype(float))


base_de_dados_performace

C:\Users\dsant\AppData\Local\Temp\ipykernel_15828\472043173.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base_de_dados_performace['1 Year'] = (base_de_dados_performace['1 Year'].astype(float))

AttributeError: Can only use .str accessor with string values!

# Outros

In [ ]:
#ler HTML - Pandas

tabela_final = pd.read_html(html_tabela)[0]

print(tabela_final)

In [ ]:
display(tabela_final)

In [ ]:
# ler tabala
   
   
print(html_tabela)